### ISSUE TITLE
Follow python packaging conventions

### ISSUE THREAD

**Issue by sbliven** [sagivba/pdb_prep#1]
This tool fails to follow standard packaging conventions, which makes it hard to install. See https://packaging.python.org/ for info.

- Source code should be within a top-level `pdb_prep` directory
- All source directories should have `__init__.py` files so that python recognizes them as modules
- The software should be installable with `python setup.py install`
- There should be a `__main__.py` that runs the main entry point (pdb_prep.py). This allows the tool to be run as `python -m pdb_prep`. You  might also want to install an [entry point script](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html).
- requirements (e.g. click) should be listed in setup.py and/or requires.txt

**Comment by sagivba** [comment]
Our team improved the setup.py file
Now installation can be done using "pip install pdb_prep"
